#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = "log"
editor = "vim"

[user]
name = "Nawasan Wisitsingkhon"
email = "zocketzero@proton.me"

[signing]
backend = "gpg"
key = "zocketzero@proton.me"
# behavior = "own"

[templates]
# Overrides default 'jj log' format
log = 'builtin_log_compact ++ "" ++ signature_status ++ "\n"'

[template-aliases]
'signature_status' = '''
if(signature,
if (signature.display(),
  label("green", " [signed: "++ signature.status() ++ " " ++ signature.display() ++ "]"),
  label("green", " [signed: "++ label("red", signature.status()) ++ " " ++ author.name() ++ " <" ++ author.email() ++ "> " ++ "]"),
),
  label("unsigned_label", " [unsign]")
)
'''

[colors]
"unsigned_label" = "red"
"green" = "green"
"red" = "red"
